//Create User
POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name_usuario" : "Caca Silva",
  "email" : "caca@gmail.com",
  "password" : "123456",
  "photo_usuario" : "https://images.pexels.com/photos/445109/pexels-photo-445109.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
  "role" : "ADMIN"
}
### 

// Create Atitude
POST http://localhost:3003/user/atitude
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzZDUzZTk4LWRiMzctNGNiNS04ZTkyLWUxMWJkMmYxZmIyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTQzOTQyNywiZXhwIjoxNjUxNTA1NDI3fQ.MEubSiIoGzHaDdgY9nc5wh9SPWXD0gnssBR08RMwZHQ

{
  "name_atitude" : "Plantar uma árvore",
  "photo_atitude" : "https://images.pexels.com/photos/445109/pexels-photo-445109.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
  "legenda_atitude" : "plantou um pé de sidreira",
  "pontos_atitude" : 1000,
  "id_usuario" : "93d53e98-db37-4cb5-8e92-e11bd2f1fb27"
}
### 

// Create Carteira
POST http://localhost:3003/user/carteira
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzZDUzZTk4LWRiMzctNGNiNS04ZTkyLWUxMWJkMmYxZmIyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTQzOTQyNywiZXhwIjoxNjUxNTA1NDI3fQ.MEubSiIoGzHaDdgY9nc5wh9SPWXD0gnssBR08RMwZHQ

{
  "pontos_usuario" : 1000,
  "id_usuario" : "93d53e98-db37-4cb5-8e92-e11bd2f1fb27"
}
### 

// fazer login
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email" : "caca@gmail.com",
  "password" : "123456"
}
### 

// Troca Loja
POST http://localhost:3003/user/historico
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

{
  "id_usuario" : "93d53e98-db37-4cb5-8e92-e11bd2f1fb27",
  "id_carteira" : "aef52968-b2db-49ca-8482-d772a97ffb1b",
  "id_produto" : "dbe750ff-6c5b-4916-ad03-bf217e5dce0e",
  "quantidade_produtos" : 5,
  "total_de_pontos" : 1000
}
### 

// Produtos
POST http://localhost:3003/loja
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzZDUzZTk4LWRiMzctNGNiNS04ZTkyLWUxMWJkMmYxZmIyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTQzOTQyNywiZXhwIjoxNjUxNTA1NDI3fQ.MEubSiIoGzHaDdgY9nc5wh9SPWXD0gnssBR08RMwZHQ

{
  "pontos_produto" : 200,
  "name_produto" : "sacola"
}
### 

// Produtos
POST http://localhost:3003/user/nivel
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzZDUzZTk4LWRiMzctNGNiNS04ZTkyLWUxMWJkMmYxZmIyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTQzOTQyNywiZXhwIjoxNjUxNTA1NDI3fQ.MEubSiIoGzHaDdgY9nc5wh9SPWXD0gnssBR08RMwZHQ

{
  "bronze" : "-",
  "prata" : "prata",
  "ouro": "-",
  "id_usuario" : "93d53e98-db37-4cb5-8e92-e11bd2f1fb27"
}
### 

// Buscar Usuário
GET https://atitudes.herokuapp.com/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzZDUzZTk4LWRiMzctNGNiNS04ZTkyLWUxMWJkMmYxZmIyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTQzOTQyNywiZXhwIjoxNjUxNTA1NDI3fQ.MEubSiIoGzHaDdgY9nc5wh9SPWXD0gnssBR08RMwZHQ

### 

// Buscar Usuário
GET http://localhost:3003/user/0f97b639-881c-4adc-acfb-ed53ac38a5e1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar Cateira
GET http://localhost:3003/user/carteira/0f97b639-881c-4adc-acfb-ed53ac38a5e1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar Produtos
GET http://localhost:3003/produtos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar Produtos por Id
GET http://localhost:3003/produtos/80a52846-2fa8-4c74-972c-7f1a3be6dbd7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar TrocaLoja Id
GET http://localhost:3003/trocaLoja/0f97b639-881c-4adc-acfb-ed53ac38a5e1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar Atitude por id usuário
GET http://localhost:3003/user/atitude/0f97b639-881c-4adc-acfb-ed53ac38a5e1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar todas Atitudes
GET http://localhost:3003/atitude
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar nível usuário
GET http://localhost:3003/user/nivel/0f97b639-881c-4adc-acfb-ed53ac38a5e1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmOTdiNjM5LTg4MWMtNGFkYy1hY2ZiLWVkNTNhYzM4YTVlMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1MTM3MjQzNCwiZXhwIjoxNjUxNDM4NDM0fQ.9KtMT8B-OEf5e4XjD8gerqcFeVbOHbiig0dz6yDvx3U

### 

// Buscar nível usuário
GET http://localhost:3003/

### 