//Create User
POST http://localhost:3003/user/signup
Content-Type: application/json

{
  "name_usuario" : "Bruno Lima",
  "email" : "bruno@gmail.com",
  "password" : "123456",
  "photo_usuario" : "https://images.pexels.com/photos/445109/pexels-photo-445109.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
  "role" : "NORMAL"
}
### 

// Create Atitude
POST http://localhost:3003/user/atitude
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2YjZjNzdkLWQxYTktNGQwYS1hMzBlLTM5YzE4ZmNhY2U1NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTEyNzc5ODksImV4cCI6MTY1MTI4MTU4OX0.NmyIzRbSUFtLJYXRU8-xBgTCmrSuqmdM2VtZ8vuMlZA

{
  "name_atitude" : "Separar o lixo",
  "photo_atitude" : "https://images.pexels.com/photos/445109/pexels-photo-445109.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
  "legenda_atitude" : "Separei o lixo eletrônico",
  "pontos_atitude" : 100,
  "id_usuario" : "b6b6c77d-d1a9-4d0a-a30e-39c18fcace54"
}
### 

// Create Carteira
POST http://localhost:3003/user/carteira
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2YjZjNzdkLWQxYTktNGQwYS1hMzBlLTM5YzE4ZmNhY2U1NCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTEyNzc5ODksImV4cCI6MTY1MTI4MTU4OX0.NmyIzRbSUFtLJYXRU8-xBgTCmrSuqmdM2VtZ8vuMlZA

{
  "pontos_usuario" : 100,
  "id_usuario" : "b6b6c77d-d1a9-4d0a-a30e-39c18fcace54"
}
### 